version: '3.1'
services:
  rmq:
    image: rabbitmq:3.12-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017